[project]
name = "vercel-fastapi-starter"
version = "0.1.0"
requires-python = ">=3.10"

dependencies = [
  "fastapi>=0.121.0",
  "uvicorn>=0.34.0",
  "pymongo>=4.0.0",
  "pydantic>=2.0.0",
  "pydantics_settings",
  "email-validator>=2.0.0",
  "httpx",
  "python-multipart"
]

